runtime: java21
instance_class: F1

env_variables:
  SPRING_DATA_MONGODB_URI: "mongodb+srv://joeldsouza132004_db_user:b9l3kVadFbkBwOqk@cluster1.shdqnec.mongodb.net/journaldb?retryWrites=true&w=majority"
  SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: "true"

automatic_scaling:
  max_instances: 5
  min_instances: 0
  target_cpu_utilization: 0.65

entrypoint: java -Xmx256m -jar journals-0.0.1-SNAPSHOT.jar