runtime: java21

env_variables:
  SPRING_DATA_MONGODB_URI: "mongodb+srv://joeldsouza132004_db_user:b9l3kVadFbkBwOqk@cluster1.shdqnec.mongodb.net/journaldb?retryWrites=true&w=majority"
  SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: "true"

entrypoint: java -Xmx512m -jar journals-0.0.1-SNAPSHOT.jar